### ISSUE TITLE
After soft reset or HASS restart, DHT sensor doesn't register

### ISSUE THREAD

**Issue by mastershake8241** [OttoWinter/esphomelib#100]
Setup is a nodemcu v2, with a DHT22 powered by the 3.3v pin. It has a builtin resistor on it's little board it came with. The problem is after a soft reset by pushing the nodemcu's button to reset it, or a restart of HASS it doesn't see the DHT22 sensor is connected anymore unless I physically disconnect and reconnect the sensor or pull it's power cord to the nodemcu and reconnect it. I see this output when it's not working and it will output this until 1 of the 2 things happens above. I let it go for a couple hours to see if it would fix itself.

`[08:19:39][W][sensor.dht:118]: Falling edge for bit -1 failed!
[08:19:39][W][sensor.dht:059]: Invalid readings! Please check your wiring (pull-up resistor, pin_ number) and consider manually specifying the DHT model using the model option. Error code: 0`

I also wrote a basic DHT22 firmware for it and uploaded to test if it was the sensors or the nodemcu and with just the generic DHT esp8266 library it has no problem continuing to see the sensor after multiple soft resets and outputting the temp/humidity.

My config file is:
```
esphomeyaml:
  name: kitchen
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: '********'
  password: '********'

mqtt:
  broker: '192.168.1.121'
  username: ''
  password: ''

# Enable logging
logger:

ota:

sensor:
  - platform: dht
    pin: D4
    temperature:
      name: "Kitchen Temp"
    humidity:
      name: "Kitchen Humidity"
    model: DHT22
```
