### ISSUE TITLE
Can't use relay's or GPIO for sensors

### ISSUE THREAD

**Issue by mastershake8241** [OttoWinter/esphomelib#101]
I add the code for using a relay but it doesn't pass the verify step.
*Nodemcu V2

```
ERROR [esphomeyaml.config] Unable to find component sensor.gpio
Failed config
  General Error: 
    - Platform not found: sensor.gpio
```

Code:
```
esphomeyaml:
  name: garage
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: '********'
  password: '********'

mqtt:
  broker: '192.168.1.121'
  username: ''
  password: ''

# Enable logging
logger:

ota:

sensor:
# Temperature/Humidity Sensor
  - platform: dht
    pin: D4
    temperature:
      name: "Garage Temp"
    humidity:
      name: "Garage Humidity"
    model: DHT22
# Garage Door
  - platform: gpio
    pin: D3
    name: "Garage Door"
```
