### ISSUE TITLE
ESP32S Starts AP Mode when unspecifed

### ISSUE THREAD

**Issue by GreenTentacle** [OttoWinter/esphomelib#103]
Hi !  I love ESPHOMELIB, but have run into 1 weird issue.

After an (undetermined) time period, with my esp32s still connected to my wifi, I see an SSID pop up of the form `ESP_xxxxx`-- it's unsecured and if I connect to it (and get a 192.168.4.x IP from DHCP), I can see the esphome webpage (if I've enabled it).  If I specify ap settings in the yaml, I believe the same thing happens when it is connected in STA mode.

This is the config where it's definitely reproducible
```
esphomeyaml:
  name: homebeacon
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: 'mywifiSSID'
  password: 'mypassword'
  hostname: blebeacon
  domain: .apartment.local
    
mqtt:
  broker: 'myMQTTbrokersIP'
  username: ''
  password: ''

# Enable logging
logger:

# temporarily disabled
#ota:

# temporarily disabled
#web_server:
#  port: 80

binary_sensor:
  - platform: status
    name: "Home BLE Beacon Status"

esp32_ble_beacon:
  type: iBeacon
  uuid: 'a UUID I chose'
  major: 111
  minor: 1

status_led:
  pin: GPIO2
```
