### ISSUE TITLE
MQTT command to toggle a component

### ISSUE THREAD

**Issue by escoand** [OttoWinter/esphomelib#138]
I would like to toggle a light of an other esphomelib device. This is currently just possible when subscribing to the state topic of the destination device but not with a toggle MQTT telegram.
What do you think about this additional command?

**Comment by OttoWinter** [comment]
I mean for such use-case it would be pretty easy I believe to just use the [`on_message`](https://esphomelib.com/esphomeyaml/components/mqtt.html#on-message) trigger to do anything you want:

```yaml
# Node A
mqtt:
  on_message:
    topic: my/toggle/topic
    then:
      - switch.toggle:
          id: my_switch
```

```yaml
# Node B
on_...:
  # Toggle switch on other node
  mqtt.publish:
    topic: my/toggle/topic
    payload: TOGGLE
```

I do not really intend to add a specific toggle command to the MQTT frontend if it's not really too big of a use-case + it's possible in other ways.
