### ISSUE TITLE
On_toggle automation

### ISSUE THREAD

**Issue by conor-o-brien** [OttoWinter/esphomelib#150]
Hi, is it possible to have an automation similar to `on_click` and `on_double_click` but instead with `on_toggle` and `on_double_toggle` that could be used with a wall switch. 
This simple sketch has the functionality [https://github.com/Dullage/SwitchedSonoffSimple](url).
I hope this is the right place to ask this, sorry if not.

**Comment by OttoWinter** [comment]
Yes, yes this is the right place to ask. Currently the only way to do so is to use the `on_press` and `on_release` triggers and duplicating the action in there. But an `on_toggle` seems like a good idea.

For now, you can do this (have the same content inside `on_press` and `on_release`):

```yaml
binary_sensor:
  - platform: ...
    # ...
    on_press:
      - switch.toggle: my_switch
    on_release:
      - switch.toggle: my_switch
```
