### ISSUE TITLE
Pulse counter

### ISSUE THREAD

**Issue by voicevon** [OttoWinter/esphomelib#165]
I am using pulse sensor, the value unit is "pulse/min". I hope there are two measure unit. First is "Total pulses count" ,it is for "How many pulses the sensor has caught". Second is "Rate/Ratio", Just same requirement as currently what the pulse sensor is doing. Further more, I want the third value like "Acceleration", to show how much it's going faster/slower.  
I tried to modify the code, But it should be one GPIO connected, Like the behavior of DHT-11, two sensors with one wire. This will be a challenge for me. @OttoWinter , Do you think my idea is doable?
I know we should consider about the counter overflow, power-down, might be other troubles I don't know right now.

BTW: one document error at https://esphomelib.com/api/sensor/pulse_counter.html  at "Example usage"
```
strom_warme.mqtt->set_unit_of_measurement("kW");
strom_warme.mqtt->clear_filters();
strom_warme.mqtt->add_multiply_filter(0.06f); // convert from Wh pulse to kW
```
the mqtt is wrong, should be pcnt.

**Comment by OttoWinter** [comment]
Yes, it is possible:

```yaml
sensor:
  - platform: pulse_counter
    filters:
      - lambda: |-
          static float total_value = 0.0;
          // 0.25 because of update_interval 15s
          total_value += x * 0.25;
          return total_value;
```

The acceleration would be more or less the same, but I'll leave it as an exercise to the reader :P
