### ISSUE TITLE
Turning effect off freezes light in effect state until change

### ISSUE THREAD

**Issue by TheJulianJES** [OttoWinter/esphomelib#166]
Fix for this issue: #169

(Edit 2: now also tried on digital strips, and it occurs on all effects that are present)

When turning off an effect, the lights freeze in the current state (e.g. Strobe remains white // off, when turning the effect to none) until you change one of the light values (brightness, color,...)
(Hass still reports the proper values, which the light should have)

(Board: NodeMCUv2, esp8266, hassio esphomeyaml addon "bleeding-edge" -> currently 1.8.1)
(Also, the strobe effect always uses the white color but I guess that is intended?)

Relevant config entry:
```
output:
  - platform: esp8266_pwm
    pin: D0
    id: red_output
  - platform: esp8266_pwm
    pin: D4
    id: green_output
  - platform: esp8266_pwm
    pin: D8
    id: blue_output

light:
  - platform: rgb
    name: "led_1_strip"
    id: leds
    red: red_output
    green: green_output
    blue: blue_output
    gamma_correct: 1.0
    effects:
      - random:
      - strobe:
      - flicker:
```

(Edit 1: When the strobe effect currently displays the bright phase, and ```{"state": "ON", "effect": "None"}``` is then called, it stops in the white phase.)
