### ISSUE TITLE
ADC values are not sent frequently enough

### ISSUE THREAD

**Issue by stoefln** [OttoWinter/esphomelib#224]
**ESP8266:**
NodeMcu v2

**Affected component:**
https://esphomelib.com/esphomeyaml/components/mqtt.html

**Description of problem:**
I configured an update interval of 5s for my sensor, but the value is only sent every minute or so.
I would need the value every 5s.
Is there a way to configure the sensor to send it every 5 seconds? 
A work around would be for me to configure the sensor to send the value immediately if it rises above a certain threshold.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: adc
    pin: A0
    name: "ADC Val"
    update_interval: 5s
```
