### ISSUE TITLE
v1.9.2 breaks mqtt_subscribe sensor

### ISSUE THREAD

**Issue by emwap** [OttoWinter/esphomelib#294]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
hass.io

**ESP (ESP32/ESP8266/Board/Sonoff):**
ESP8266

**Affected component:**
https://esphomelib.com/esphomeyaml/components/sensor/mqtt_subscribe.html

**Description of problem:**
I have a custom component that reads the state of two input sensors, one of which is a `mqtt_subscribe` sensor.
In the custom component `update` method I test if the input sensors contain `NAN`. If either sensor is `NAN` the method returns and skips further processing.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: mqtt_subscribe
    name: "IVT490 Target Temperature"
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    accuracy_decimals: 1
    id: ivt490_target_temp
    topic: /ivt/new_temp
    filters:
      - filter_nan:
      - lambda: return x/10.0f;
      - heartbeat: 60s
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
```

**Traceback (if applicable):**
N/A

**Additional information:**
The code works fine on v1.9.1 but fails silently on v1.9.2.
Only the `mqtt_subscribe` sensor is stuck at `NAN`. The other input sensor is updated.
I can see the `/ivt/new_temp` message on the MQTT network.
