### ISSUE TITLE
logger: VERBOSE causes 'SYSTEM_EVENT_AP_STAIPASSIGNED' was not declared in this scope

### ISSUE THREAD

**Issue by tringler** [OttoWinter/esphomelib#320]
Hello,

I have a strange behaviour with `logger:` - If I set it to `VERBOSE` with that configuration I get `.piolibdeps/esphomelib/src/esphomelib/wifi_component.cpp:183:10: error: 'SYSTEM_EVENT_AP_STAIPASSIGNED' was not declared in this scope`

```
esphomeyaml:
  name: floor
  platform: ESP32
  board: nodemcu-32s
  arduino_version: espressif32@1.0.2

wifi:
  ssid: SSID
  password: password4Wifi

logger:
  level: VERBOSE
```
If I remove `level: VERBOSE` it compiles successfully.
