### ISSUE TITLE
mqtt_json platform depreciated in Homeassistant 0.84

### ISSUE THREAD

**Issue by cbrherms** [OttoWinter/esphomelib#321]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

All

**ESP (ESP32/ESP8266/Board/Sonoff):**

All

**Affected component:**

All components that use the mqtt_json platform as output

**Description of problem:**
Changes to mqtt lights in homeassistant made `mqtt_json` platform depreciated, this is now incorporated in to one platform, `light.mqtt`, with the type of mqtt light configured via a schema. 
This should only affect devices set up via mqtt discovery using the old type of config, and users who manually setup their lights in configuration.yaml
Pull that implemented this and describes the change is here: https://github.com/home-assistant/home-assistant/pull/18227

**Problem-relevant YAML-configuration entries:**

Old configuration entry
```yaml
light:
  - platform: mqtt_json
    command_topic: "home/rgb1/set"
```

New entry
```yaml
light:
  - platform: mqtt
    schema: json
    command_topic: "home/rgb1/set"
```

**Traceback (if applicable):**

```

```

**Additional information:**

Due to the depreciation above, in HA 0.84.1 devices set up as light produce a warning as still using the old setup via Mqtt discovery
