### ISSUE TITLE
Individually addressable lights/sub-led-strips

### ISSUE THREAD

**Issue by WoLpH** [OttoWinter/esphomelib#330]
**Is your feature request related to a problem/use-case? Please describe.**

I have a few large led strips that I would like to split up virtually so I can control parts of the led strips as different devices. I know that I could physicially split the strips and connect them to different digital ports, but that would require a lot of extra wiring and work and there really shouldn't be any need for that.

One actual use-case I have lined up already. I have a [DreamScreen](https://www.dreamscreentv.com/) (philips ambilight like device) which controls a bunch of leds behind my TV directly. But it has the option of connecting "external" devices as well which would allow me to control the led strips I have near the ceiling in a few different parts.

**Describe the solution you'd like**
Right now we have mqtt commands like these:
```
device_name/light/light_name/command
```

I think there are a few different options for these. The simplest solution might be supporting something like this:
```
device_name/light/light_name/led_number/command
```
With the regular payload like this:
```json
{"color": {"r": 1, "g": 1, "b": 0}}
```

Or perhaps keep the original command and simply allow for an array of values as payload:
```json
{"color": [{"r": 1, "g": 0, "b": 0}, {"r": 0, "g": 1, "b": 0}, {"r": 0, "g": 0, "b": 1}]}
```

Another option could be to allow for sub-led strip assignments but I think that might be harder to code internally. The configuration would be rather simple, simply a regular addressable led strip config with an added led-offset parameter. For example:
```yaml
light:
  - platform: fastled_clockless
    name: "Group 0"
    chipset: WS2811
    pin: D1
    offset: 0
    num_leds: 10
  - platform: fastled_clockless
    name: "Group 1"
    chipset: WS2811
    pin: D1
    offset: 10
    num_leds: 10
  - platform: fastled_clockless
    name: "Group 2"
    chipset: WS2811
    pin: D1
    offset: 20
    num_leds: 10
```

I personally think implementing an array of colors would be easiest for this use case without any backwards compatibility issues.
