### ISSUE TITLE
dev branch: error: 'class esphomelib::WiFiComponent' has no member named 'set_sta'

### ISSUE THREAD

**Issue by DavidDeSloovere** [OttoWinter/esphomelib#331]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
hassio

**ESP (ESP32/ESP8266/Board/Sonoff):**
esp8266 wemos d1 mini

**Affected component:**
wifi

**Description of problem:**
Compile with **DEV** branch (`esphomelib_version: dev`) not working with wifi settings.

**Problem-relevant YAML-configuration entries:**
```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.71
    gateway: 192.168.0.1
    subnet: 255.255.255.0
```

**Traceback (if applicable):**
```
Compiling .pioenvs/wemos_bandit_scrappy/lib4d9/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:14:19: error: 'class esphomelib::WiFiComponent' has no member named 'set_sta'
_wificomponent->set_sta(::WiFiAp{
^
src/main.cpp:14:27: error: '::WiFiAp' has not been declared
_wificomponent->set_sta(::WiFiAp{
^
*** [.pioenvs/wemos_bandit_scrappy/src/main.cpp.o] Error 1
```

**Additional information:**
Also tried commenting out `manual_ip` block, but that does't seem to matter.
