### ISSUE TITLE
mqtt_on_message doesn't subscribe to broker

### ISSUE THREAD

**Issue by voicevon** [OttoWinter/esphomelib#335]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hassio.

**ESP (ESP32/ESP8266/Board/Sonoff):**
Esp32 NodeMcu and Esp8266_NodeMCU
**Affected component:**
MQTT_client_component 

**Description of problem:**
on_message is never triggered. 

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: feeder
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: 'xxxx'
  password: 'xxxx'
switch:
  - platform: gpio
    name: motor_p1
    pin: 5
  - platform: gpio
    name: motor_p2
    pin: 4 
mqtt:
  broker: 'xxxx'
  username: 'xxxx'
  password: 'xxxx'
  on_message: 
    - topic: abcd/efgh
      then:
        - delay: 10s
```

**Traceback (if applicable):**
Got subscription of the two gpio, but could not find topic from mqtt_client_component.
```
␛[0;32m[I][mqtt.client:211]: MQTT Connected!␛[0m
␛[0;36m[D][mqtt.client:316]:    subscribe(topic='feeder/switch/motor_p1/command')␛[0m
␛[0;36m[D][mqtt.client:316]:    subscribe(topic='feeder/switch/motor_p2/command')␛[0m
```

**Additional information:**
#315 
I could  not find any information about topic "abcd/efgh".  the topic is never being subscript.
sometimes the mqtt is disconnected ->connected. I can see the re-subscription of the two gpio_switch_command.  but never seen "abcd/efgh". At least I want to know, am I the only one who is facing this issue?
