### ISSUE TITLE
WiFi connection issue - info v1.9.3

### ISSUE THREAD

**Issue by mspinolo** [OttoWinter/esphomelib#342]
**Operating environment/Installation (Hass.io/Docker/pip/etc.): Latest Hassbian, HA 0.84.6

**ESP (ESP32/ESP8266/Board/Sonoff): Sonoff T1 & Sonoff Basic

**Affected component: WIFI connections stability

**Description of problem: inconsistent WIFi connection when i switched from my old network config (see below for details) to my new one based on RT2600ac + MR2200ac as mesh router. The latter connected to RT2600ac by ethernet for backhaul connection.
Previous situation was super stable with 1-2 wifi connection drops of all my sonoff (6).
Switching to the new config brought me back to something similar to 1.7.0 esphomelib version with 40-50 drops per day.

I then changed DTIM setting on my router from 4 to 2 and now I am back to 1-2 drops per day: intention is not to report and esphomelib bug but more to help in case this information could be helpful to improve basic WIFI stability.

**Problem-relevant YAML-configuration entries: 
```yaml
wifi:
  ssid: 'MYSSID'
  password: 'XXX'
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: XXX
    # Set this to the IP address of the router. Often ends with .1
    gateway: XXXX
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: XXXX

mqtt:
  broker: 'my_broker_ip'
  username: 'myuser'
  password: 'mypass'
  keepalive: 7s
```

**Traceback (if applicable):**

```
N/A
```

**Additional information: previous router config used was synology RT2600ac as main router and 2011 (I think) Airport Extreme as access point with same SSID name (RT2600ac being on wifi channel 11, Airport on channel 1)
