### ISSUE TITLE
Deep Sleep makes home assistant list sensor as "Unknown"

### ISSUE THREAD

**Issue by rutberg** [OttoWinter/esphomelib#412]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Hassio

**ESP (ESP32/ESP8266/Board/Sonoff):** Nodemcuv2

**Affected component:** https://esphomelib.com/esphomeyaml/components/deep_sleep.html

**Description of problem:** The suggested fix in the component readme about changing the will_message and birth_message dosen't yield the desired result. Instead the MQTT connection times out and the status in Home Assistant becomes Unknown

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: garage
  platform: ESP8266
  board: nodemcuv2

mqtt:
  broker: 192.168.1.159
  birth_message:
  will_message:
  on_message:
    topic: garage/ota_mode
    payload: "ON"
    then:
      - deep_sleep.prevent: deep_sleep_1
      - logger.log: "OTA_mode enabled, halting deep sleep"



wifi:
  ssid: 'WIFISSID'
  password: 'WIFIPSWD'
  manual_ip:
    static_ip: 192.168.1.140
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:
 level: INFO
# Enable Home Assistant API
api:
  password: 'PSWD'
ota:
  password: 'PSWD'
sensor:
  - platform: dht
    model: DHT22
    pin: D5
    temperature:
      name: "Garage Temperature"
    humidity:
      name: "Garage Humidity"
    update_interval: 8s

deep_sleep:
  id: deep_sleep_1
  run_duration: 10s
  sleep_duration: 60s

```

**Traceback (if applicable):**

```

```

**Additional information:**
I've also tried the mentioned fix; to set the keep alive to a number greater than the sleep duration, but home assistant still drops the sensor during sleep.
I'm running MQTT Server & Web client component as MQTT broker.
