### ISSUE TITLE
Wifi connection issue after defining light component

### ISSUE THREAD

**Issue by timmmmmmmmm** [OttoWinter/esphomelib#416]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266/Board/Sonoff):**
Sonoff Basic

**Affected component:**
Wifi functionality

**Description of problem:**
I'm trying to flash an Sonoff Basic with a firmware that makes the relay shows up in Home Assistant as a light component. I defined an output and consequently link the light component to it. The code runs fine without the light component defined, but once I add it . The moment I include the light component in the code the ESP8266 isn't able to detect any wifi networks on boot. The serial logs repeatingly:
```
[0;36m[D][wifi:260]: Starting scan...[0m
[0;36m[D][wifi:275]: Found networks:[0m
[0;36m[D][wifi:277]:   No network found![0m
```
After keeping this running for a while (5 minutes) it finally detects (only) my network and connects, but disconnects right after. When I don't include the light component it lists all networks around me and stays connected to my network without a problem. Did I configure something wrong or did I encounter a bug here?

**Problem-relevant YAML-configuration entries:**
```yaml
output:
  - platform: gpio
    id: sonoff_relay
    pin: GPIO12

light:
  - platform: binary
    name: "Moonlight"
    output: sonoff_relay
```

**Traceback (if applicable):**
n/a

```

```

**Additional information:**
n/a
