### ISSUE TITLE
Compiling DHT for ESP8266 fails, because of OTA stuff

### ISSUE THREAD

**Issue by simonszu** [OttoWinter/esphomelib#43]
Relevant YAML-configuration, (besides the wizard-autogen-stuff):
```
ota:
  password: 'changeme'

sensor:
  - platform: dht
    pin: D4
    temperature:
      name: "Serverschrank Temperatur"
    humidity:
      name: "Serverschrank Luftfeuchtigkeit"
    update_interval: 15s
```
Relevant output of the run command:
```
Compiling .pioenvs/serverschrankklima/lib959/esphomelib/esphomelib/sensor/ads1115_component.cpp.o
Compiling .pioenvs/serverschrankklima/lib959/esphomelib/esphomelib/sensor/bmp085_component.cpp.o
Compiling .pioenvs/serverschrankklima/lib959/esphomelib/esphomelib/sensor/dallas_component.cpp.o
.piolibdeps/esphomelib/src/esphomelib/ota_component.cpp: In member function 'virtual void esphomelib::OTAComponent::setup()':
.piolibdeps/esphomelib/src/esphomelib/ota_component.cpp:40:18: error: 'class ArduinoOTAClass' has no member named 'setPasswordHash'
ArduinoOTA.setPasswordHash(this->password_.c_str());
^
*** [.pioenvs/serverschrankklima/lib959/esphomelib/esphomelib/ota_component.cpp.o] Error 1
```

Removing the OTA part of the config does not fix this issue. 

Otherwise, great piece of work, i appreciate very much. Sometimes i'm just too lazy to code my own firmware ;)
