### ISSUE TITLE
I2C interface stalls sometimes

### ISSUE THREAD

**Issue by njbuch** [OttoWinter/esphomelib#434]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Ubuntu 18.04 running Homeassistant 0.85.1
**ESP (ESP32/ESP8266/Board/Sonoff):**

ESP32
**Affected component:**

**Description of problem:**
I am running and ESP32 with a temp-sensor and i small display. It works most of the time, but sometimes after a while, the display freezes and stops being updated. A reset of the device does not help, I need to plug the power to the device and restart it.

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: test1
  platform: ESP32
  board: lolin32
  arduino_version: latest

wifi:
  ssid: 'secret'
  password: 'secret'
  # ...
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.secret.secret
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.secret.secret
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: True
  password: VERYSECURE
  
switch:
  - platform: gpio
    name: "Internal Blue LED"
    pin: 22

# Example configuration entry
i2c:
  sda: 19
  scl: 23
  scan: True

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      id: bme280_temperature
    pressure:
      name: "BME280 Pressure"
      id: bme280_pressure
    humidity:
      name: "BME280 Realtive Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 60s
  - platform: template
    name: "Altitude"
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(bme280_temperature).state + 273.15) / 0.0065) * (powf((STANDARD_SEA_LEVEL_PRESSURE / id(bme280_pressure).state), 0.190234) - 1); // in meter
    update_interval: 60s
  - platform: template
    name: "Absolute Humidity"
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_temperature).state) / (id(bme280_temperature).state + 243.5)) * id(bme280_humidity).state * mw) / ((273.15 + id(bme280_temperature).state) * r); // in grams/m^3
    update_interval: 60s

# Example configuration entry
time:
  - platform: homeassistant
    id: homeassistant_time

font:
#  - file: "tinymce.ttf"
  - file: "comic.ttf"
    id: my_font
    size: 12
  - file: "comic.ttf"
    id: my_big_font
    size: 24

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    # reset_pin: D0
    address: 0x3C
    lambda: |-
      it.strftime(0, 0, id(my_font), "%Y-%m-%d %H:%M", id(homeassistant_time).now());
      it.print(0, 15, id(my_font), "Temp");
      it.print(64, 15, id(my_font), "RelHum");
      it.printf(0, 39, id(my_big_font), "%.1f", id(bme280_temperature).state);  
      it.printf(64, 39, id(my_big_font), "%.0f%", id(bme280_humidity).state);  
      it.line(0, 16, 128, 16);
      it.line(0, 0, 128, 0);
      it.print(0, 50, id(my_font), "Temp Sensor A1");

```

**Traceback (if applicable):**

```
␛[0;32m[I][application:053]: Running through setup()...␛[0m
[E][esp32-hal-i2c.c:1146] i2cCheckLineState(): Bus Invalid State, TwoWire() Can't init
␛[0;35m[C][switch.gpio:023]: Setting up GPIO Switch 'Internal Blue LED'...␛[0m
␛[0;36m[D][switch:055]: 'Internal Blue LED': Sending state ON␛[0m
␛[0;35m[C][display.ssd1306:301]: Setting up I2C SSD1306...␛[0m
␛[0;33m[W][i2c:084]: Too much data to fit in transmitter buffer for address 0x3C␛[0m
␛[1;31m[E][component:163]: Component was marked as failed.␛[0m
␛[0;35m[C][sensor.bme280:090]: Setting up BME280...␛[0m
␛[0;33m[W][i2c:084]: Too much data to fit in transmitter buffer for address 0x76␛[0m
␛[1;31m[E][component:163]: Component was marked as failed.␛[0m

```

**Additional information:**
