### ISSUE TITLE
ESP8266: Only pins 0-16 support PWM

### ISSUE THREAD

**Issue by meekell** [OttoWinter/esphomelib#59]
I'm attempting to assign a PWM output to GPIO16 of my ESP8266-12E. When attempting to compile, I'm receiving the error: _ERROR [esphomeyaml.config] Error while reading config: ESP8266: Only pins 0-16 support PWM. 

My yaml includes the following:

```
esphomeyaml:
  platform: ESP8266
  board: esp12e

output:
  - platform: esp8266_pwm
    pin: 16
    id: redPin
```
