### ISSUE TITLE
Ok, now I understand, so you want to have all three units show up as sensor at the same time.

### ISSUE THREAD

**Issue by Airfranse** [OttoWinter/esphomelib#596]
Ok, now I understand, so you want to have all three units show up as sensor at the same time.

```yaml
sensor:
- platform: pulse_counter
  name: "Pulses per minute"
  id: pulse
  filters:
- platform: template
  name: "Total pulses"
  lambda: |-
    static float total_value = 0.0;
    // 0.25 because of update_interval 15s
    total_value += id(pulse).value * 0.25;
    return total_value;
- platform: template
  name: "Pulse Acceleration"
  lambda: |-
    // ...
```

In pure C++ it would be similar, just with the use of the `TemplateSensor` class.

_Originally posted by @OttoWinter in https://github.com/esphome/esphome-core/issues/165#issuecomment-427770711_
