### ISSUE TITLE
witty cloud with LDR and  RGB

### ISSUE THREAD

**Issue by lpt2007** [OttoWinter/esphomelib#598]
Hi,

I try to use witty cloud LDR and RGB.

![160422_witty_cloud_01-1-768x595](https://user-images.githubusercontent.com/38924279/67486469-61401000-f66c-11e9-9d31-c0113566c955.jpg)

For LDR sensor I try like this but I have error in script:

```
sensor:
  - platform: adc
    pin: A0
    name: Illuminance
    unit_of_measurement: lux
    filters:
      - lambda: (x * 3.3 / 10000.0) * 2000000.0
```
