### ISSUE TITLE
Output pin `inverted` configuration broken

### ISSUE THREAD

**Issue by aequitas** [OttoWinter/esphomelib#72]
Discovered while trying example from docs: (https://github.com/OttoWinter/esphomedocs/pull/7)

This config is valid, but does not work:
```
output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin: GPIO13
    inverted: true
```

There is no difference in the generated `main.cpp` files if `inverted` is changed from true/false or even is ommited.

Current working configuration:

```
output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: true
```
