### ISSUE TITLE
Feature request: internal/hidden components

### ISSUE THREAD

**Issue by aequitas** [OttoWinter/esphomelib#77]
As mentioned in https://github.com/OttoWinter/esphomedocs/pull/10

It would be nice if some components (like switches) could be marked in such a way that they are not exposed in MQTT or the web interface. In the example given I use 2 switches to control relays for a cover motor. I don't want to expose these switches to mqtt/homeassistant as there is logic around them for interlocking. So I only want them to be controlled through the cover component.

I've been thinking about two possible implementations:

Explicit by using a flag (eg: internal, hidden, etc):
```yaml
  switch:
    - platform: gpio
      pin: 12
      name: open
      id: open
      internal: true
```

Or implicit by not specifying a name for the component (it can still be used in automations as that uses the id instead of a name:
```yaml
  switch:
    - platform: gpio
      pin: 12
      id: open
```

Currently my workaround is to 'hide' them from homeassistant by disabling their discovery:
```yaml
  switch:
    - platform: gpio
      pin: 12
      name: open
      id: open
      # 'hide' this from homeassistant as we don't want it to be controller directly
      discovery: false
```
