### ISSUE TITLE
[Idea] LEDEffect component

### ISSUE THREAD

**Issue by Diaoul** [OttoWinter/esphomelib#97]
WS2812 (AKA Neopixel) LED strips are very powerful but can be hard to work with as effects have to be implemented on the device and cannot be managed entirely remotely through Home Assistant.
So over time I created an [MQTT Template component](https://github.com/home-assistant/home-assistant/pull/4233), added [Light effects](https://github.com/home-assistant/home-assistant/pull/4538) and more recently worked on my own [LEDEffect library](https://github.com/Diaoul/LEDEffect/) that bridges FastLED+Effects with MQTT+JSON so it can be controlled with Home Assistant using my previous contributions.

You made a great job with esphomelib, I'm eager to try it out however I don't have any "dumb" ESP8266, all have some LED strips attached :sob: 

Does your library currently handle the case for programmable LED strips? If not, do you have some plans for it? I'd be happy to discuss some level of integration of the LEDEffect library with esphomelib, I think it would be a very neat integration.

**Comment by OttoWinter** [comment]
So there is already the FastLED light component: https://esphomelib.com/esphomeyaml/index.html#light-components which handles these individually addressable LED strips.

But that integration doesn't have too many light effects yet. I'm not a big fan of modifying the JSON payload for the MQTT JSON light though, as that would require special automations in the Hass configuration. I'm planning to rework the effects in esphomelib a bit to allow at least for some parameterization of settings. The syntax would look like this:


```yaml
light:
  - platform: fastled_clockless
    # ...
    effects:
      - rainbow:
          name: "Slow Rainbow Effect"
          speed: 42s # or whatever this option would be called
      - rainbow:
          name: "Fast Rainbow Effect"
          speed: 1s
      # or when no parameters specified defaults to some values
      - rainbow:
      - random:
      - colorwheel:
```

This way the user has complete controls of which effects can be used and can even parameterize them quite quickly without messing with sending custom MQTT messages in HA.
